### ISSUE TITLE
Clarification needed on data analysis results

### ISSUE THREAD

**Issue by adafnos** [nicolarighetti/CooRTweet#27]
Hi, 

I've tried to use the package with my own data, but I do not fully understand the results generated by the `account_stats()` function.

My dataset includes the following: `1. "tweet_id", 2. "retweet_id", "user_id", "created_at"`.

Following your suggestion, I used the `prep_data()` function:

`coord_tweets <- prep_data(tweets, object_id = "retweet_id", account_id = "user_id", content_id = "tweet_id", timestamp_share = "created_at")`

and also:

```
result <- detect_groups(coord_tweets, min_participation = 10, time_window = 300)
coord_graph <- generate_coordinated_network(result, edge_weight = 0.99, objects = TRUE)
summary_accounts <- account_stats(coord_graph, result, weight_threshold = "full")
```

but the results suggest that one of the users has shared a total of 2950 unique posts; however, in the initial dataset (i.e. `tweets`) this user's id appears only 284 times, which means that this user has tweeted or retweeted only 284 posts. 

I'm a bit confused about this discrepancy, am I doing something wrong?

Thanks for your help!

**Comment by nicolarighetti** [comment]
Hello @adafnos,

Thank you for reporting this issue! I've examined the issue using simulated data to replicate your process and have made an update that may resolve the problem you're experiencing. Could you please update to the latest version of the package and check if the issue still persists?

To update the package, you can use the following command in R:

```
# Install devtools if you haven't already
install.packages("devtools")

# Then install the CooRTweet package directly from GitHub using devtools
devtools::install_github("nicolarighetti/CooRTweet")

# Load the package
library(CooRTweet)
```

**Comment by adafnos** [comment]
Hi @nicolarighetti ,

Thank you for your reply and for fixing this issue! 

The results make sense now, the user I mentioned yesterday appears to have shared 250 unique posts.

**Comment by nicolarighetti** [comment]
Thank you for confirming that the issue has been resolved!

I will proceed to close this issue now. If there are any more related problems or questions in the future, feel free to reopen this issue or create a new one. 

Thanks again for your contribution!
